name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  docker:
    name: Release Container Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/hello-world
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: azure/setup-helm@v4
        with:
          version: v3.19.0

      - name: Determine chart version
        id: chart_version
        run: |
          # Use dev version by default
          CHART_VERSION="v$(git describe --tags)"

          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Use tag version
            CHART_VERSION="${GITHUB_REF_NAME}"
          fi
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: helm package chart --version ${{ steps.chart_version.outputs.version }}
      - run: helm push hello-world-${{ steps.chart_version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

  ocm:
    name: Release OCM component
    runs-on: ubuntu-latest

    needs:
      - docker
      - helm

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: open-component-model/ocm-setup-action@30210abb7373f34003cd50cdab77e23497afa6a7

      - name: Retrieve image versions from imagevector
        run: yq '.images[] | ((.name | sub("-"; "_") | upcase) + "_VERSION=" + .tag)' imagevector/images.yaml >> $GITHUB_ENV

      - name: Determine OCM component version and destination repository
        id: ocm_info
        run: |
          # Use dev version and repo by default
          gitsha=$(echo ${{ github.sha }} | cut -c1-7)
          OCM_VERSION="v0.0.0+${gitsha}"
          CHART_VERSION="$(git describe --tags)"
          IMAGE_VERSION="sha-${gitsha}"
          OCM_REPO="ghcr.io/${{ github.repository_owner}}/ocm-dev"

          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Use tag version and production repo
            OCM_VERSION="${GITHUB_REF_NAME}"
            CHART_VERSION="${GITHUB_REF_NAME}"
            IMAGE_VERSION="${GITHUB_REF_NAME}"
            OCM_REPO="ghcr.io/${{ github.repository_owner}}/ocm"
          fi
          echo "version=$OCM_VERSION" >> $GITHUB_OUTPUT
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "image_version=$IMAGE_VERSION" >> $GITHUB_OUTPUT
          echo "repository=$OCM_REPO" >> $GITHUB_OUTPUT

      - name: Add OCM component version to transport archive
        run: ocm add components --create --file ocm/ctf ocm/component-constructor.yaml --addenv
        env:
          VERSION: ${{ steps.ocm_info.outputs.version }}
          IMAGE_VERSION: ${{ steps.ocm_info.outputs.image_version }}
          CHART_VERSION: ${{ steps.ocm_info.outputs.chart_version }}

      - name: Tranfer OCM component transport archive to GitHub Container Registry
        run: ocm transfer ctf ocm/ctf ${OCM_REPO}
        env:
          OCM_REPO: ${{ steps.ocm_info.outputs.repository }}
